const fs = require('fs');
let html = fs.readFileSync('baseline.html', 'utf8');
const script = html.match(/<script>\s*([\s\S]*?)<\/script>/)[1];
html = html.replace(/<script>\s*[\s\S]*?<\/script>/, '<script src="app.js"></script>');
html = html.replace('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js', '../node_modules/xlsx/dist/xlsx.full.min.js');
html = html.replace('</head>', '<link rel="stylesheet" href="studio.css"></head>');
html = html.replace('<meta charset="UTF-8" />', '<meta charset="UTF-8" /><meta http-equiv="Content-Security-Policy" content="default-src \'self\'; script-src \'self\'; style-src \'self\' \'unsafe-inline\'; img-src \'self\' data: blob:; connect-src \'none\'; object-src \'none\'; base-uri \'none\'">');
html = html.replace('<main>', `<main><header class="workspace-bar"><span>WORKSPACE <span class="breadcrumb">/ Untitled experiment</span></span><div><span id="saveStatus">Local workspace</span><button class="btn small" id="globalSave">Save project</button></div></header><div id="staleNotice" class="callout hidden">Your data or analysis settings have changed. Run analysis to update results and graphs.</div>`);
html = html.replace('ΔΔCt analysis workspace', 'FROM DISCOVERY TO FIGURE');
html = html.replace('<div class="logo">qP</div>', '<div class="logo">◌</div>');
html = html.replace('<div class="nav">','<div class="nav-label">YOUR EXPERIMENT</div><div class="nav">');
html = html.replace('Import & clean','Data workspace').replace('Analysis setup','Analysis setup').replace('Calculations','Results').replace('Graphs & stats','Figure studio');
html = html.replace('<div class="sideNote">','<div class="sideNote"><span class="offline-dot"></span> OFFLINE & PRIVATE<br><br>');
html = html.replace('Import raw qPCR data','Good science starts here.').replace('Bring in one or more Excel/CSV files and review the raw Ct/Cq values before analysis.','Bring your raw data into focus. Import, refine, and move from Ct values to your next discovery.');
html = html.replace('<div class="grid two">', `<div class="welcome-strip"><div><span class="eyebrow">THE COMPLETE qPCR WORKFLOW</span><h3>Less spreadsheet.<br>More science.</h3><p>A thoughtful space for every step of your experiment.</p><button class="btn" id="exploreDemo">Explore an example <span>↗</span></button></div><div class="molecule" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><span>ΔΔCt</span></div><div class="workflow-mini"><span>01 <b>Import & refine</b></span><span>02 <b>Normalize & analyze</b></span><span>03 <b>Make it a figure</b></span></div></div><div class="section-heading"><h3>Your data</h3><span>Excel and CSV · all processed on your device</span></div><div class="grid two">`);
html = html.replace('Excel import uses SheetJS from a public CDN. CSV import works without that library.','Excel and CSV import work offline.');
html = html.replace('Graphs & statistical tests','Your data, beautifully expressed.');
html = html.replace('Change the display, edit plotted values without altering raw data, and compare biological replicates.','Create a figure, fine-tune every color, and explore your biological replicates.');
html = html.replace('<h3>Graph controls</h3>', `<div class="eyebrow">MAKE IT YOURS</div><h3>Figure settings</h3><div class="style-panel"><div class="field"><label for="palettePreset">Color palette</label><select id="palettePreset"><option value="botanical">Botanical</option><option value="ocean">Ocean</option><option value="accessible">Colorblind friendly</option><option value="custom">Custom</option></select></div><div id="colorSwatches" class="color-swatches"></div><div class="fields"><div class="field"><label for="pointSize">Point size</label><input id="pointSize" type="range" min="2" max="8" value="4.5" step="0.5"></div><div class="field"><label for="barOpacity">Bar opacity</label><input id="barOpacity" type="range" min="0.1" max="1" value="0.7" step="0.05"></div></div><label class="switch"><input id="showGrid" type="checkbox" checked> Show gridlines</label></div>`);
html = html.replace('For publication-quality figures, export the calculated CSV and finish styling in GraphPad Prism/R if needed. This view is intended for fast QC, exploration, and routine analysis.','Export your figure as a high-resolution PNG. Colors and figure settings are included when you save a project.');
html = html.replace('id="statsUseOverrides" type="checkbox" checked','id="statsUseOverrides" type="checkbox"');
html = html.replace('</body>', '<div id="toast" role="status" aria-live="polite"></div></body>');
fs.writeFileSync('src/index.html', html);
let js = script.replace("const num = v => { const x = Number(v);", "const num = v => { if(v === null || v === undefined || String(v).trim() === '') return null; const x = Number(v);");
js = js.replace("const $ = s =>", `const palettes = {botanical:['#547b69','#bc865b','#879cc2','#b18eb3','#c8b768','#668f9c','#a77978','#7d8580'],ocean:['#397c96','#54a9b3','#827eb7','#d09a62','#7189aa','#7fa587','#b57c97','#88949e'],accessible:['#0072b2','#e69f00','#009e73','#cc79a7','#56b4e9','#d55e00','#8a7900','#555555']};
  let colors=[...palettes.botanical];
  const $ = s =>`);
js = js.replaceAll("const palette=['#3157d5','#1d8a60','#b36a00','#8a4fd0','#d14f6f','#2a8fb8','#687385','#d17f2b'];", 'const palette=colors;');
js = js.replace(/const conditionPalette=\[[^;]+;/, 'const conditionPalette=colors;').replace(/const trialPalette=\[[^;]+;/, 'const trialPalette=colors;');
js = js.replaceAll('hexAlpha(geneColor,.18)', "hexAlpha(geneColor,Number($('#barOpacity').value))").replaceAll('hexAlpha(c,.70)', "hexAlpha(c,Number($('#barOpacity').value))");
js = js.replace('ctx.arc(x,y,4.5,0,Math.PI*2)', "ctx.arc(x,y,Number($('#pointSize').value),0,Math.PI*2)");
js = js.replaceAll("ctx.strokeStyle='#e6eaf0'", "ctx.strokeStyle=$('#showGrid').checked?'#e6eaf0':'transparent'");
js = js.replace('const dpr=window.devicePixelRatio||1;', 'const dpr=Math.max(2,window.devicePixelRatio||1);');
js = js.replace('trial.rowCount=norm.length;', "if(!norm.length) throw new Error('No valid numeric Ct/Cq rows found. Blank and undetermined values are ignored.'); trial.rowCount=norm.length;");
js = js.replaceAll('state.analysisRun=false', 'invalidate()');
js = js.replace("state.selectedGenes.clear();renderSetup()", "state.selectedGenes.clear();invalidate();renderSetup()");
js = js.replace("state.selectedGenes.add(g));renderSetup()", "state.selectedGenes.add(g));invalidate();renderSetup()");
js = js.replace("if(v!==null)r.cq=v;", "if(v!==null)r.cq=v;else {e.target.value=r.cq;toast('Enter a numeric Ct value, or exclude the well.');return;}");
js = js.replace("if(f==='sample' && old!==r.sample)", "if(!r[f]){r[f]=old;e.target.value=old;return;} if(f==='sample' && old!==r.sample)");
js = js.replace("function parseCSV(text){", "function parseCSV(text){if(window.XLSX){const wb=XLSX.read(text,{type:'string',raw:true});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});}");
js = js.replace("const oldSelected=new Set($$('[data-graph-gene]:checked').map(x=>x.value));", ()=>"const oldSelected=new Set(state.pendingGraphGenes||$$('[data-graph-gene]:checked').map(x=>x.value));if(genes.length)delete state.pendingGraphGenes;");
js = js.replace('state.results=res; state.analysisRun=true;', "state.results=res; state.analysisRun=true; $('#staleNotice').classList.add('hidden'); toast('Analysis complete · '+res.length+' trial-level values');");
js = js.replace("if(name==='graphs') {", "if((name==='graphs'||name==='results') && state.raw.length && !state.analysisRun){ if(!runAnalysis()) return; renderResults(); renderGraphControls(); } if(name==='graphs') {");
js = js.replace("const payload={version:1,", "const payload={version:2,figure:getFigure(),");
js = js.replace("state.overrides=p.overrides||{};", "state.overrides=p.overrides||{}; restoreFigure(p.figure); $('#efficiency').value=state.base===2?'2':'custom'; $('#customBase').value=state.base; $('#customBaseField').classList.toggle('hidden',state.base===2);");
js = js.replace("const p=JSON.parse(await e.target.files[0].text());", "if(!e.target.files.length)return; const p=JSON.parse(await e.target.files[0].text()); validateProject(p);");
js = js.replace("function csvCell(v){const s=v==null?'':String(v);", "function csvCell(v){let s=v==null?'':String(v); if(typeof v==='string' && /^[=+@-]/.test(s))s=\"'\"+s;");
js = js.replace("a.download=name;a.click();", "a.download=name;a.click();toast('Exported '+name);");
js = js.replace("const rangeVals=[...vals];", "const ends=groups.flatMap(g=>{const v=g.map(p=>p.v), a=mean(v), e=$('#errorType').value==='sem'?sem(v):$('#errorType').value==='sd'?sd(v):0;return [a-e,a+e]}).filter(v=>Number.isFinite(v)&&(yscale!=='log'||v>0)); const rangeVals=[...vals,...ends];");
js = js.replace("const y=v=>m.t+(ymax-transform(v))/(ymax-ymin)*plotH", "const y=v=>m.t+(ymax-transform(yscale==='log'?Math.max(v,10**ymin):v))/(ymax-ymin)*plotH");
js = js.replace("const tv=rangeVals.map(transform)", "const tv=rangeVals.filter(v=>yscale!=='log'||v>0).map(transform)");
js = js.replace('let rows=state.results.filter(r=>genes.includes(r.gene) && graphRowVisible(r,metric) && Number.isFinite(valueFor(r,metric,true)));', "let rows=state.results.filter(r=>genes.includes(r.gene) && graphRowVisible(r,metric) && Number.isFinite(valueFor(r,metric,true)) && (yscale!=='log'||valueFor(r,metric,true)>0));");
const enhancement = fs.readFileSync('scripts/enhancements.txt','utf8');
// Keep dense figures compact instead of expanding the exported canvas per category.
js = js.replace(/    \/\/ Keep x-axis labels horizontal\.[\s\S]*?    const cssHeight=/, `    const parentWidth=Math.max(320,wrap.clientWidth||wrap.getBoundingClientRect().width||800);
    const desiredWidth=Math.min(820,parentWidth);
    const cssHeight=`);
js = js.replace("const multi=genes.length>1; const m={l:70,r:24,t:58,b:multi?92:72};", "const multi=genes.length>1; const axisLabels=categories.map(cat=>multi?cat.gene+' · '+cat.condition:cat.condition); const axis=compactAxis(ctx,axisLabels,W,categories.length); const m={l:axis.left,r:24,t:58,b:axis.bottom};");
js = js.replace(/    ctx.textAlign='center';ctx.textBaseline='top';categories.forEach\(\(cat,i\)=>\{[\s\S]*?\n    \}\);/, "    categories.forEach((cat,i)=>drawAngledLabel(ctx,axisLabels[i],xCenter(i),H-m.b+12,axis));");
js = js.replace("const m={l:72,r:26,t:86,b:70},", "const axis=compactAxis(ctx,genes,W,genes.length); const m={l:axis.left,r:26,t:86,b:axis.bottom},");
js = js.replace('const gap=4;', 'const gap=Math.min(4,clusterW/(Math.max(1,activeConds.length)*5));');
js = js.replace('const barW=Math.max(10,Math.min(42,(clusterW-gap*Math.max(0,activeConds.length-1))/Math.max(1,activeConds.length)));', 'const barW=Math.min(42,(clusterW-gap*Math.max(0,activeConds.length-1))/Math.max(1,activeConds.length));');
js = js.replace("ctx.font='700 11px system-ui';ctx.textAlign='center';ctx.textBaseline='top';ctx.fillStyle='#1d2939';ctx.fillText(gene,gx,H-m.b+11);", "drawAngledLabel(ctx,gene,gx,H-m.b+12,axis);");
js = js.replace('  refreshAll();\n})();', ()=>enhancement+'\n  refreshAll();\n})();');
// Replace the original JavaScript calculation/plot engines, not just their UI.
js=js.replace(/  function runAnalysis\(\)\{[\s\S]*?  function eqGene/, '  function eqGene');
js=js.replace(/  function drawChart\(\)\{[\s\S]*?  \/\/ Export\/save/, '  // Export/save');
js=js.replace(/  \$\('#downloadPng'\)\.onclick=.*?;\n/, '');
js=js.replace('function showPage(name){','async function showPage(name){');
js=js.replace('if(!runAnalysis()) return;', 'if(!await runAnalysis()) return;');
js=js.replace("$('#runAnalysis').onclick=()=>{ if(runAnalysis())", "$('#runAnalysis').onclick=async()=>{ if(await runAnalysis())");
js=js.replace('function invalidate(){','function invalidate(){\n    dataRevision++;previewRevision++;clearTimeout(previewTimer);');
js=js.replace('  refreshAll();\n})();',()=>fs.readFileSync('scripts/python-ui.txt','utf8')+'\n  refreshAll();\n})();');
fs.writeFileSync('src/app.js', js);
html=html.replace('<canvas id="chart"></canvas>','<img id="chart" alt="qPCR figure generated by Matplotlib" hidden><div id="chartStatus" role="status">Run analysis to create a figure.</div>');
html=html.replace('Download graph PNG','Export PNG');
html=html.replace('2× resolution export','PNG · SVG · PDF');
html=html.replace('Export your figure as a high-resolution PNG.', 'Export your figure as a 300 DPI PNG or a vector SVG/PDF.');
fs.writeFileSync('src/index.html', html);
